### PR TITLE
Add `jupyterlite-xeus-sqlite`

### PR DESCRIPTION
**Pull request by jtpio**
Now developed in https://github.com/jupyterlite/xeus-sqlite-kernel

And available on PyPI: https://pypi.org/project/jupyterlite-xeus-sqlite/

### CODE REVIEW

**Comment by jtpio** [comment]
cc @DerThorsten if you have an example notebook around that we could add to the demo site

**Comment by DerThorsten** [comment]
@jtpio no so far I have no good demo notebook. @marimeireles might have something which does not need a pre-existing notebook

**Comment by jtpio** [comment]
Probably we can reuse this one and create the new db in memory: https://github.com/jupyter-xeus/xeus-sqlite/blob/master/examples/Simple%20operations.ipynb

**Comment by jtpio** [comment]
Looking good locally with the built archive:

image

**Comment by DerThorsten** [comment]
@jtpio I am glad to see that the vega stuff just works!

**Pull request merged**
