### PR TITLE
Update examples in line with main repo examples

### PR DESCRIPTION
**Pull request by psychemedia**
- update example notebooks to be in line with main repo `examples`
- reorganise `examples`

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks!

Do you think we'll need to periodically update them? Trying to think how this will work in the long term when the upstream examples are updated or new ones are added.

An alternative could be to download the notebooks from the `jupyterlite` upstream repo in the CI workflow. But that would complicate the setup in this repo which is meant to be used as a template and simple to start with.

**Comment by psychemedia** [comment]
Being able to feed off the main repo would be the best bet. 

One loosely coupled way would be to git-clone from the main repo and then just feed of the necessary bits (which might mean a slight refactoring of requirements files in the main repo into a requirements file that is minimally complete for the examples? Unless you try to parse out the packages from imports but there isn't always a 1-1 mapping from package name to pypi package name, and universal wheels may not be available; also, versions wouldn't be controlled.)

I don't think you can include just a small part/subdirectory of one repo in another using git submodules which would have provided another way.

If there were an examples repo, I guess that could be included as a submodule in both the main jupyterlite repo and the demo repo, but then you not only have the problem of an exploding number of repos, but also circularity in trying to figure how best to test the examples.

**Comment by jtpio** [comment]
Submodules can be really hard to deal with and make things more complicated.

So we can probably stick to a bunch of normal files for now, and see how things go.

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
Would you like to submit a similar PR upstream as part of https://github.com/jupyterlite/jupyterlite/issues/168 and https://github.com/jupyterlite/jupyterlite/issues/150?

**Comment by psychemedia** [comment]
That's where I made the start, but I can't get things to work properly in my `jupyerlite` envt atm (eg the widgets not rendering). I think that's an artefact of something in that environment (hmm, or maybe the browser cache?) but I don't want to push something that I *think* should work for other people and just doesn't work for me. (And re: running tests: one day, I will get my head round running and writing tests...!)

**Comment by jtpio** [comment]
Ah ok. We can always use the ReaTheDocs preview on the PR to check the changes.

**Pull request merged**
